### ISSUE TITLE
UnboundLocalError: local variable 'junit_type' referenced before assignment

### ISSUE THREAD

**Issue by stffrdhrn** [YosysHQ/sby#143]
After some recent junit work I am getting an the below failure. 

The variable `junit_type` is not defined and we get error:

```
SBY 22:09:12 [mor1kx_dcache_prv] summary: Elapsed clock time [H:MM:SS (secs)]: 0:00:15 (15)
SBY 22:09:12 [mor1kx_dcache_prv] summary: Elapsed process time [H:MM:SS (secs)]: 0:00:05 (5)
SBY 22:09:12 [mor1kx_dcache_prv] summary: engine_0 (smtbmc) returned FAIL for basecase
SBY 22:09:12 [mor1kx_dcache_prv] summary: counterexample trace: mor1kx_dcache_prv/engine_0/trace.vcd
SBY 22:09:12 [mor1kx_dcache_prv] DONE (FAIL, rc=2)
Traceback (most recent call last):
  File "/home/arch/local/yosys/bin/sby", line 469, in <module>
    task_retcode = run_task(task)
  File "/home/arch/local/yosys/bin/sby", line 458, in run_task
    task.print_junit_result(f, junit_ts_name, junit_tc_name, junit_format_strict=False)
  File "/home/arch/local/yosys/bin/../share/yosys/python3/sby_core.py", line 791, in print_junit_result
    print(f'<failure type="{junit_type}" message="{self.status}" />', file=f)
UnboundLocalError: local variable 'junit_type' referenced before assignment
make: *** [Makefile:45: mor1kx_dcache] Error 1
make: Leaving directory '/home/arch/work/openrisc/local-cores/mor1kx/bench/formal'
```

_Originally posted by @stffrdhrn in https://github.com/YosysHQ/sby/pull/133#r830383648_

**Comment by stffrdhrn** [comment]
The PR that introduced this was from @nakengelhardt
